export type Operation = 'AUREON' | 'GR-INVEST';
export type Message = {id:string; text:string; from:'lead'|'agent'|'bot'|'system'; time:string; attachment?:{name:string;url?:string;type:string}};
export type Activity = {id:string;text:string;time:string;by:string};
export type Proposal = {id:string;value:number;entry:number;months:number;installment:number;plan:string;notes:string;status:string;date:string};
export type Lead = {id:string;name:string;photoUrl?:string;phone:string;email:string;cpf:string;city:string;state:string;operation:Operation;source:string;campaign:string;utm_source:string;utm_medium:string;utm_content:string;created:string;updated:string;stage:string;status:string;agent:string;score:number;value:number;entry:number;income:number;objective:string;term:number;tags:string[];unread:number;messages:Message[];activities:Activity[];proposals:Proposal[];docs:{name:string;type:string;url?:string}[];qualification?:Record<string,string>;followup?:string};
export type Task = {id:string;leadId:string;operation:Operation;title:string;agent:string;due:string;priority:string;done:boolean};
export type Appointment = {id:string;leadId:string;operation:Operation;title:string;date:string;type:string;agent:string};
export type Member = {id:string;name:string;email:string;operation:Operation;role:string;online:boolean;response:number};
export type Rule = {id:string;operation:Operation;name:string;trigger:string;action:string;delay:number;message:string;active:boolean};
export type Campaign = {id:string;name:string;operation:Operation;source:string;budget:number;active:boolean};
export type SettingsData={monthlyGoal:number;distribution:string;botActive:boolean;handoff:number;botGreeting:string;followups:number[];followupText:string;agentGoals?:Record<string,number>};
export type Store = {leads:Lead[];tasks:Task[];appointments:Appointment[];team:Member[];rules:Rule[];campaigns:Campaign[];settings:SettingsData&{byOperation?:Partial<Record<Operation,SettingsData>>};audit:Activity[]};
export function settingsFor(store:Store,op:Operation|'TODOS',write=false):SettingsData{
 if(op==='TODOS')return store.settings;
 if(write&&!store.settings.byOperation?.[op]){const {byOperation,...base}=store.settings;store.settings.byOperation={...byOperation,[op]:structuredClone(base)};}
 return store.settings.byOperation?.[op]||store.settings;
}
export const stages=['Lead recebido','Contato realizado','Qualificação','Simulação','Proposta','Negociação','Documentação','Fechamento','Convertido','Perdido'];
export const statuses=['Em atendimento','Fila','Não atendidos','Aguardando resposta','Follow-up','Finalizados'];
export const uid=()=>crypto.randomUUID();
export const money=(n:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(n);
export const compact=(n:number)=>n>=1e6?`R$ ${(n/1e6).toFixed(1).replace('.',',')} mi`:n>=1e3?`R$ ${(n/1e3).toFixed(0)} mil`:money(n);
export const initials=(s:string)=>s.split(' ').slice(0,2).map(x=>x[0]).join('');
export const temperature=(score:number)=>score>=70?'Quente':score>=40?'Morno':'Frio';
export const localDay=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
export const clock=(date=new Date())=>date.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});
export function scoreQualification(q:Record<string,string>,value:number,entry:number,income:number){
  const criteria=[{label:'Orçamento compatível',points:entry>=value*.15?20:entry>0?10:0},{label:'Urgência',points:q.urgency==='Alta'?15:q.urgency==='Média'?8:3},{label:'Interesse demonstrado',points:q.knowledge==='Sim'?10:5},{label:'Capacidade financeira',points:income>=value*.015?20:income>0?10:0},{label:'Renda comprovada',points:q.proof==='Sim'?15:0},{label:'Prazo de contratação',points:q.when==='Este mês'?10:q.when==='Até 3 meses'?7:3},{label:'Perfil de crédito',points:q.restrictions==='Não'?10:0}];
  return {score:criteria.reduce((sum,c)=>sum+c.points,0),criteria};
}
export function seed():Store {
  const today=localDay();
  const samples=[['Carlos Henrique','AUREON','Meta Ads',550000,80000,82,'Proposta','Em atendimento','Mariana Costa','Tenho interesse em uma carta de R$ 550 mil.'],['Fernanda Oliveira','AUREON','Google Ads',420000,65000,76,'Simulação','Em atendimento','Mariana Costa','Consegue me enviar uma simulação?'],['Rafael Mendes','GR-INVEST','Indicação',900000,180000,93,'Negociação','Em atendimento','Lucas Almeida','Podemos conversar sobre a proposta hoje?'],['Juliana Santos','AUREON','Instagram',320000,40000,58,'Qualificação','Fila','Pedro Lima','Quais documentos preciso enviar?'],['André Ribeiro','AUREON','Meta Ads',650000,120000,88,'Documentação','Follow-up','Mariana Costa','Vou analisar com minha esposa e te retorno.'],['Beatriz Lima','GR-INVEST','Landing Page',480000,70000,45,'Contato realizado','Aguardando resposta','Lucas Almeida','Estou procurando meu primeiro imóvel.'],['Marcelo Duarte','AUREON','WhatsApp',750000,160000,96,'Convertido','Finalizados','Pedro Lima','Recebi o contrato. Muito obrigado!'],['Camila Ferreira','GR-INVEST','Google Ads',380000,35000,33,'Lead recebido','Não atendidos','Lucas Almeida','Gostaria de entender como funciona.'],['Thiago Souza','AUREON','Orgânico',600000,95000,72,'Fechamento','Em atendimento','Mariana Costa','Pode preparar a proposta final.'],['Patrícia Rocha','GR-INVEST','Meta Ads',1100000,240000,91,'Convertido','Finalizados','Lucas Almeida','Tudo certo, proposta aprovada!'],['Bruno Martins','AUREON','Facebook',280000,20000,24,'Perdido','Finalizados','Pedro Lima','Vou deixar para outro momento.'],['Larissa Gomes','GR-INVEST','Instagram',520000,90000,79,'Proposta','Follow-up','Lucas Almeida','Obrigada pela apresentação.']];
  const leads=samples.map((s,i):Lead=>{const [name,operation,source,value,entry,score,stage,status,agent,last]=s; const id=`lead-${i+1}`;
    return {id,name:String(name),phone:`+55 (11) 9${String(87423010+i*317).slice(0,4)}-${String(87423010+i*317).slice(-4)}`,email:String(name).toLowerCase().split(' ')[0]+'@exemplo.com',cpf:'000.000.000-00',city:i%3===0?'São Paulo':i%3===1?'Campinas':'Santos',state:'SP',operation:operation as Operation,source:String(source),campaign:operation==='AUREON'?'Seu próximo capítulo':'Investir com visão',utm_source:String(source).toLowerCase(),utm_medium:'paid_social',utm_content:'criativo_01',created:new Date(today+'T09:00:00').toISOString(),updated:new Date(today+'T14:32:00').toISOString(),stage:String(stage),status:String(status),agent:String(agent),score:Number(score),value:Number(value),entry:Number(entry),income:18000,objective:i===2?'Investir':'Comprar imóvel',term:12,tags:i===0?['Alto ticket','Primeiro imóvel']:i===2?['Investidor','Urgente']:['Crédito imobiliário'],unread:i===0?2:i<5?1:0,followup:today+'T16:00',messages:[{id:id+'m1',from:'bot',text:`Olá, ${String(name).split(' ')[0]}! Sou o Assistente Comercial da ${operation}. Como posso ajudar você a realizar seu próximo objetivo?`,time:'14:18'},{id:id+'m2',from:'lead',text:i===0?'Olá! Estou buscando crédito para comprar meu primeiro imóvel em São Paulo.':String(last),time:'14:20'},{id:id+'m3',from:'agent',text:i===0?'Olá, Carlos! Sou a Mariana, especialista da Aureon. Será um prazer ajudar você nessa conquista. Qual o valor do imóvel que tem em mente?':'Perfeito! Vou avaliar seu perfil e preparar as melhores opções para o seu objetivo.',time:'14:24'},{id:id+'m4',from:'lead',text:String(last),time:'14:32'}],activities:[{id:uid(),text:'Lead recebido via '+source,time:today+'T14:18',by:'Sistema'},{id:uid(),text:'Pré-qualificação iniciada',time:today+'T14:19',by:'Assistente Comercial'},{id:uid(),text:'Atendimento assumido',time:today+'T14:24',by:String(agent)}],proposals:i===0?[{id:'PROP-001',value:550000,entry:80000,months:180,installment:3200,plan:'Crédito imobiliário',notes:'Simulação ilustrativa. Condições sujeitas à análise e validação comercial.',status:'Criada',date:today}]:[],docs:[]};});
  return {leads,tasks:[{id:uid(),leadId:'lead-1',operation:'AUREON',title:'Enviar simulação personalizada',agent:'Mariana Costa',due:today+'T15:00',priority:'Alta',done:false},{id:uid(),leadId:'lead-5',operation:'AUREON',title:'Retomar análise da proposta',agent:'Mariana Costa',due:today+'T16:00',priority:'Alta',done:false},{id:uid(),leadId:'lead-3',operation:'GR-INVEST',title:'Confirmar reunião de negociação',agent:'Lucas Almeida',due:today+'T17:00',priority:'Média',done:false}],appointments:[{id:uid(),leadId:'lead-3',operation:'GR-INVEST',title:'Apresentação de proposta · Rafael',date:today+'T15:30',type:'Reunião',agent:'Lucas Almeida'},{id:uid(),leadId:'lead-1',operation:'AUREON',title:'Simulação · Carlos Henrique',date:today+'T16:30',type:'Ligação',agent:'Mariana Costa'}],team:[{id:'member-1',name:'Mariana Costa',email:'mariana@exemplo.com',operation:'AUREON',role:'Atendente',online:true,response:3},{id:'member-2',name:'Lucas Almeida',email:'lucas@exemplo.com',operation:'GR-INVEST',role:'Supervisor',online:true,response:4},{id:'member-3',name:'Pedro Lima',email:'pedro@exemplo.com',operation:'AUREON',role:'Atendente',online:false,response:6}],rules:[{id:uid(),operation:'AUREON',name:'Recepção e pré-qualificação',trigger:'Lead entrou',action:'Enviar mensagem',delay:0,message:'Olá! Seja bem-vindo à Aureon. Qual o seu objetivo de crédito?',active:true},{id:uid(),operation:'AUREON',name:'Prioridade para leads quentes',trigger:'Score acima de 70',action:'Enviar para fila',delay:0,message:'Seu perfil foi analisado. Vou encaminhar você para um especialista.',active:true},{id:uid(),operation:'GR-INVEST',name:'Retomar proposta enviada',trigger:'Sem resposta',action:'Criar tarefa',delay:1440,message:'Olá! Conseguiu analisar nossa proposta?',active:true}],campaigns:[{id:uid(),name:'Seu próximo capítulo',operation:'AUREON',source:'Meta Ads',budget:5000,active:true},{id:uid(),name:'Investir com visão',operation:'GR-INVEST',source:'Google Ads',budget:3500,active:true}],settings:{monthlyGoal:3000000,distribution:'Round Robin',botActive:true,handoff:70,botGreeting:'Olá 👋 Seja bem-vindo. Sou o Assistente Comercial. Vamos encontrar uma opção para seu objetivo?',followups:[30,1440,4320,10080,21600],followupText:'Olá {nome}, conseguiu analisar a simulação que enviamos? Estou à disposição para ajudar.'},audit:[]};
}
